# fos_rest:
#     param_fetcher_listener: true
#     body_listener: true
#     format_listener: true
#     view:
#         view_response_listener: 'force'

fos_rest:
    routing_loader:
        default_format: json
    param_fetcher_listener: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    # disable_csrf_role: ROLE_USER
    body_converter:
        enabled: true
    view:
        view_response_listener: force
        # jsonp_handler: ~

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600


sensio_framework_extra:
    request: { converters: true }
    view:    { annotations: false }
    router:  { annotations: true }