sonata_admin:
    title: 'SSCM - Admin'
    # title_logo: 'bundles/sadmin/images/logo-ss.jpg'
    dashboard:
        blocks:

            - { position: left, type: sonata.block.service.text, settings: { content: "<div class='panel panel-default'><div class='panel-heading'> <h3 class='panel-title'> Bienvenido!</h3> </div><div class='panel-body'> Sistema Administrativo Sala Situacional, adscrita a la Universidad Bolivariana de Venezuela (UBV Sede Zulia), un espacio de análisis permanente donde se emplean las herramientas tecnológicas apropiadas para gestionar los datos académicos, administrativos y la participación de los diferentes sectores, por esa variación dinámica, en el ámbito social se planteó la necesidad de adaptarse a las nuevas transformaciones del entorno tecnológico de manera inmediata. La innovación, la rapidez, el servicio de gran calidad, el ritmo al que se mejora y aplica el conocimiento constituyen las nuevas reglas del juego. En el mundo de hoy, la dedicación y la aportación de fuerza laboral son decisivas y la información es el arma esencial en esta batalla. </div></div> "} }
            - { position: right, type: sonata.admin.block.admin_list}

        # groups:
        #     sonata.admin.group.regions:
        #         label:			Regiones
        #         icon:  '<i class="fa fa-play-circle"></i>'
        #         items:
        #             - sonata.sscm.admin.listpais
        #             - sonata.sscm.admin.listestado