services:
    sonata.sscm.admin.listpais:
         class:  SSCM\SadminBundle\Admin\ListPaisAdmin
         tags:
             -  { name: sonata.admin, manager_type: orm, group: 'Regiones ', label: Pais }
         arguments:
             - null
             - SSCM\SadminBundle\Entity\ListPais
             - null
         # calls:
         #    - [ setTranslationDomain, [SonataAdminBundle]]