services:
    sonata.sscm.admin.alumno:
        class: SSCM\CipeeBundle\Admin\AlumnoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Alumnos", label: "Estudiantes" }

        arguments:
            - ~
            - SSCM\CipeeBundle\Entity\Alumno
            - ~

        # calls:
        #     - [addChild, ["@sonata.sscm.admin.estado"]]