<?php

namespace SSCM\CipeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MallaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MallaRepository extends EntityRepository
{
}
