<?php

namespace SSCM\CipeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PfgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PfgRepository extends EntityRepository
{
}
